#
name: lottery-app
environment: dev

logging:
  level:
    .: debug
    org.springframework: DEBUG
  file: ${HOME}/logs/lottery.log

server:
  port: 5000

app:
  name: lottery-app
  dir: ${user.home}/.${app.name}
  db-name: lottery
  db-host: localhost
  db-port: 5432
  db-username: postgres
  db-password: postgres
  db-url-prefix: jdbc:postgresql://

spring:
  profiles: dev
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: ${app.db-url-prefix}${app.db-host}:${app.db-port}/${app.db-name}
    initialization-mode: never
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
      show_sql: true
      use_sql_comments: true
      generate_statistics: false

